### ISSUE TITLE
Tokenizer and model not accessible 

### ISSUE THREAD

**Issue by pallucs** [alchemab/antiberta#2]
Greetings,

I am trying to fine tune your model in my own dataset. But when I instantiate the tokenizer and model through huggingface, 
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/antibody-tokenizer/resolve/main/vocab.json. This error occurs which I think is because this is a private model not available in hugginface? 

Can you give me access to the tokenizer and model?

Thankyou,
Palistha

**Comment by jleem-iso** [comment]
Hi! The antibody tokenizer is pretty simple, and in fact it's in the root directory of the repo. We are not distributing model weights, though you should be able to run the pre-training code to generate your own LM.

**Comment by pallucs** [comment]
Thankyou for your reply
