### ISSUE TITLE
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like antiberta-master is not the path to a directory containing a {configuration_file} file.

### ISSUE THREAD

**Issue by AliakseiBelabrovik** [alchemab/antiberta#4]
![image](https://user-images.githubusercontent.com/71708619/199593596-9d920471-b6c7-4945-bf94-6a7abeea7a3b.png)
I get an OSError while trying to run the paratope-prediction.ipynb.
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like antiberta-master is not the path to a directory containing a {configuration_file} file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

Can you help me and tell me what I am doing wrong? I have the internet connection. Perhaps MODEL_DIR must be adjusted with the value "antiberta-master"?

Many thanks in advance!

**Comment by alicia-hg** [comment]
> ![image](https://user-images.githubusercontent.com/71708619/199593596-9d920471-b6c7-4945-bf94-6a7abeea7a3b.png) I get an OSError while trying to run the paratope-prediction.ipynb. OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like antiberta-master is not the path to a directory containing a {configuration_file} file. Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
> 
> Can you help me and tell me what I am doing wrong? I have the internet connection. Perhaps MODEL_DIR must be adjusted with the value "antiberta-master"?
> 
> Many thanks in advance!

**Comment by alicia-hg** [comment]
I have the same problem

**Comment by AliakseiBelabrovik** [comment]
Hi  @alicia-hg,

I have contacted the authors of the paper by email and received the reply, that the models weights have not been released (are not available for using by third parteis). That's why the error message comes that the path to the directory is not available.  However, you can train your own version of the MLM.

Best wishes, 
Aliaksei
