### ISSUE TITLE
Tokenizer not found

### ISSUE THREAD

**Issue by bprabhu-twist** [alchemab/antiberta#5]
Hi, when I try to load the tokenizer I get following error:
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/antibody-tokenizer/resolve/main/vocab.json

I was wondering if the tokenizer has been removed?

**Comment by alsanzgarcia** [comment]
> 

I also have the same problem, were you able to fix it? If so, how did you do it?

**Comment by JianquanZhao** [comment]
> Hi, when I try to load the tokenizer I get following error: HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/antibody-tokenizer/resolve/main/vocab.json
> 
> I was wondering if the tokenizer has been removed?

replace this code line as below for the authors change the model path in huggingface website 
# model = RobertaForTokenClassification.from_pretrained(MODEL_DIR, num_labels=2)
model = RobertaForTokenClassification.from_pretrained('castorini/afriberta_base')

**Comment by ragak** [comment]
I am also not able to find the antibody-tokenizer, is there a new location for this folder?

**Comment by jleem-iso** [comment]
Hi! Really sorry for the late reply, the antibody-tokenizer is in the root directory of this repo 
https://github.com/alchemab/antiberta/tree/master/antibody-tokenizer
